# Generated by Django 5.2.8 on 2025-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_city_city_image_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_ru',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
